apiVersion: v1
kind: Namespace
metadata:
  name: pro-installer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pro-installer
  namespace: pro-installer
spec:
  selector:
    matchLabels:
      job: pro-installer
  template:
    metadata:
      labels:
        job: pro-installer
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: lolwww/test:1.3
        name: pro-installer
        securityContext:
          privileged: true
        volumeMounts:
        - name: install-script
          mountPath: /tmp
        - name: host-mount
          mountPath: /host
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","./runCleanup.sh"]
      volumes:
      - name: install-script
        configMap:
          name: pro-installer
      - name: host-mount
        hostPath:
          path: /tmp/install
